vswitch bindings dynamic list widget
WayfireWM/wcm pull request #46
Opened 2023-02-17 22:52 UTC by NamorNiradnug

Fixes #35

2023-02-19 17:44 UTC, soreau requested changes
Looks good to me, aside from the few comments.

2023-02-19 17:44 UTC, soreau commented on src/wcm.cpp
> +    // label.set_size_request(OPTION_LABEL_SIZE);
Can you remove this commented line of code if it is unneeded?

2023-02-19 17:44 UTC, soreau commented on src/wcm.cpp
> +#include "metadata.hpp"
Here this include is not needed for compilation.

2023-02-19 17:44 UTC, soreau commented on src/wcm.cpp
> +#include <wayfire/config/section.hpp>
This include seems unnecessary as well.

2023-02-19 17:44 UTC, soreau commented on src/wcm.cpp
> +           color.a << ")";
Why is this indented? Have you rerun uncrustify on the code?

2023-02-19 17:44 UTC, soreau commented on src/wcm.hpp
> +#include <cstring>
Here it builds without this include..

2023-02-19 17:44 UTC, soreau commented on src/wcm.hpp
> +#include <wayfire/config/option.hpp>
and without this one. Are we using anything from these headers?

2023-02-20 11:01 UTC, NamorNiradnug commented
It was clangd automatically inserting needed headers.
Seems like it was a bad idea to enable this feature.

2023-02-20 13:39 UTC, soreau approved these changes

2023-02-20 13:40 UTC, soreau commented
> It was clangd automatically inserting needed headers. Seems like it was a bad idea to enable this feature.

Ah, well it looks better now. Thanks!

2023-02-20 13:40 UTC, merged